name: tago
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  device_preview: ^1.1.0
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.7.0
  font_awesome_flutter: ^10.3.0
  form_field_validator: ^1.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.4.0
  google_polyline_algorithm: ^3.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.5
  material_symbols_icons: ^4.39.5
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.0
  video_player: ^2.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Firma_Bold
      fonts:
        - asset: BR_firma_font/BRFirma-Bold.ttf
        - asset: BR_firma_font/BRFirma-Black.ttf
    - family: Firma_Normal
      fonts:
        - asset: BR_firma_font/BRFirma-Regular.ttf
        - asset: BR_firma_font/BRFirma-Medium.ttf
    - family: Firma_Light
      fonts:
        - asset: BR_firma_font/BRFirma-Light.ttf
        - asset: BR_firma_font/BRFirma-Thin.ttf
