name: tago
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Firma_Bold
      fonts:
        - asset: BR_firma_font/BRFirma-Bold.ttf
        - asset: BR_firma_font/BRFirma-Black.ttf
    - family: Firma_Normal
      fonts:
        - asset: BR_firma_font/BRFirma-Regular.ttf
        - asset: BR_firma_font/BRFirma-Medium.ttf
    - family: Firma_Light
      fonts:
        - asset: BR_firma_font/BRFirma-Light.ttf
        - asset: BR_firma_font/BRFirma-Thin.ttf
