name: tago
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.3.0
  form_field_validator: ^1.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.4.0
  google_polyline_algorithm: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  # intl: ^0.18.1
  intl: ^0.17.0
  material_symbols_icons: ^4.39.5
  persistent_bottom_nav_bar: ^5.0.2
  shimmer: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  webview_flutter: ^2.0.15
  url_launcher: ^6.1.14
  flutter_paystack:
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Firma_Bold
      fonts:
        - asset: BR_firma_font/BRFirma-Bold.ttf
        - asset: BR_firma_font/BRFirma-Black.ttf
    - family: Firma_Normal
      fonts:
        - asset: BR_firma_font/BRFirma-Regular.ttf
        - asset: BR_firma_font/BRFirma-Medium.ttf
    - family: Firma_Light
      fonts:
        - asset: BR_firma_font/BRFirma-Light.ttf
        - asset: BR_firma_font/BRFirma-Thin.ttf
